// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository;

#nullable disable

namespace LMS_BACKEND_MAIN.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("Id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdDate");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("EmailVerifyCode")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)")
                        .HasColumnName("EmailVerifyCode");

                    b.Property<DateTime>("EmailVerifyCodeAge")
                        .HasColumnType("datetime2")
                        .HasColumnName("EmailVerifyCodeAge");

                    b.Property<string>("FullName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("fullname");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("gender");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserRefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserRefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("verifiedBy");

                    b.Property<bool>("isBanned")
                        .HasColumnType("bit")
                        .HasColumnName("isBanned");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isDeleted");

                    b.Property<bool>("isVerified")
                        .HasColumnType("bit")
                        .HasColumnName("IsVerified");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0d0bf15f-e528-4afe-87ed-3fb8d03956cf",
                            CreatedDate = new DateTime(2024, 6, 23, 21, 18, 46, 639, DateTimeKind.Local).AddTicks(6502),
                            Email = "minhtche161354@fpt.edu.vn",
                            EmailConfirmed = true,
                            EmailVerifyCodeAge = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6513),
                            Gender = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "MINHTCHE161354@FPT.EDU.VN",
                            NormalizedUserName = "MINHTCHE161354",
                            PasswordHash = "AQAAAAIAAYagAAAAELgUn5wJH9empSyZm7MdUy84spVESi+LvNCV8nDY9PMgoY0fOBYhfZO/MPZHjSZimA==",
                            PhoneNumber = "0963661093",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "9ba7044d-2862-4115-8c25-48abc381e7ef",
                            TwoFactorEnabled = false,
                            UserName = "minhtche161354",
                            UserRefreshTokenExpiryTime = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6514),
                            isBanned = false,
                            isDeleted = false,
                            isVerified = true
                        },
                        new
                        {
                            Id = "6c6abe62-f811-4a8b-96eb-ed326c47d209",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1c110567-4e6a-4045-83ab-25cb640db893",
                            CreatedDate = new DateTime(2024, 6, 23, 21, 18, 46, 639, DateTimeKind.Local).AddTicks(6535),
                            Email = "thailshe160614@fpt.edu.vn",
                            EmailConfirmed = true,
                            EmailVerifyCodeAge = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6537),
                            Gender = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "THAILSHE160614@FPT.EDU.VN",
                            NormalizedUserName = "THAILSHE160614",
                            PasswordHash = "AQAAAAIAAYagAAAAEO5SGANyOkCieJN+MspCJeIbBLjDruXYD5omO5+7u9NVKctIo979jEts1uoDaalzTw==",
                            PhoneNumber = "0497461220",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "f2590979-cee0-4f48-8b2e-84a70343d174",
                            TwoFactorEnabled = false,
                            UserName = "thailshe160614",
                            UserRefreshTokenExpiryTime = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6537),
                            isBanned = false,
                            isDeleted = false,
                            isVerified = true
                        },
                        new
                        {
                            Id = "a687bb04-4f19-49d5-a60f-2db52044767c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e1008e2b-a5a5-4d03-9394-38f280bb4b46",
                            CreatedDate = new DateTime(2024, 6, 23, 21, 18, 46, 639, DateTimeKind.Local).AddTicks(6547),
                            Email = "hungmvhe163655@fpt.edu.vn",
                            EmailConfirmed = true,
                            EmailVerifyCodeAge = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6548),
                            Gender = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HUNGMVHE163655@FPT.EDU.VN",
                            NormalizedUserName = "HUNGMVHE163655",
                            PasswordHash = "AQAAAAIAAYagAAAAEHaY3BZO2ooRDvclwsiVvksAaPExz0GAXkEHlfwAtwfVBfRcw9gQTR02USItL9NrSg==",
                            PhoneNumber = "0975461220",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "e172a6e3-905e-4a5e-b14c-3d8f1b7f99e5",
                            TwoFactorEnabled = false,
                            UserName = "hungmvhe163655",
                            UserRefreshTokenExpiryTime = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6548),
                            isBanned = false,
                            isDeleted = false,
                            isVerified = true
                        },
                        new
                        {
                            Id = "603600b5-ca65-4fa7-817e-4583ef22b330",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c5617c84-70de-4942-8d7a-ca124ea40048",
                            CreatedDate = new DateTime(2024, 6, 23, 21, 18, 46, 639, DateTimeKind.Local).AddTicks(6560),
                            Email = "cuongndhe163098@fpt.edu.vn",
                            EmailConfirmed = true,
                            EmailVerifyCodeAge = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6561),
                            Gender = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "CUONGNDHE163098@FPT.EDU.VN",
                            NormalizedUserName = "CUONGNDHE163098",
                            PasswordHash = "AQAAAAIAAYagAAAAENVZ95qV36S0GH4gzip/nSmI9JKDA1CAGuL2+t1ysccrtPgGLrSZ6k9v/tS37ojoSw==",
                            PhoneNumber = "0975465220",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "680d8c01-96fa-49f0-80fc-44a7a229e5c3",
                            TwoFactorEnabled = false,
                            UserName = "cuongndhe163098",
                            UserRefreshTokenExpiryTime = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6562),
                            isBanned = false,
                            isDeleted = false,
                            isVerified = true
                        },
                        new
                        {
                            Id = "68fdf17c-7cbe-4a4c-a674-c530ffc77667",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "31bffa2a-a4b1-481c-a3c5-d0a176381643",
                            CreatedDate = new DateTime(2024, 6, 23, 21, 18, 46, 639, DateTimeKind.Local).AddTicks(6572),
                            Email = "hoangnmhe163884@fpt.edu.vn",
                            EmailConfirmed = true,
                            EmailVerifyCodeAge = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6573),
                            Gender = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "HOANGNMHE163884@FPT.EDU.VN",
                            NormalizedUserName = "HOANGNMHE163884",
                            PasswordHash = "AQAAAAIAAYagAAAAEBSeWGYcWJzo0jTXDBqXgYkMmzdQCRKsLrFMaaqieAdCHchkvB2oa1eRy3gsuvWyVw==",
                            PhoneNumber = "0975765220",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "ce190368-5d67-4c8c-b5c3-b98d8e4a6bfe",
                            TwoFactorEnabled = false,
                            UserName = "hoangnmhe163884",
                            UserRefreshTokenExpiryTime = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6573),
                            isBanned = false,
                            isDeleted = false,
                            isVerified = true
                        },
                        new
                        {
                            Id = "7397c854-194b-4749-9205-f46e4f2fccf8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "49d30084-6a6e-4512-896f-f4bed2fe715f",
                            CreatedDate = new DateTime(2024, 6, 23, 21, 18, 46, 639, DateTimeKind.Local).AddTicks(6583),
                            Email = "littlejohn123@gmail.com",
                            EmailConfirmed = true,
                            EmailVerifyCodeAge = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6584),
                            Gender = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "LITTLEJOHN123@GMAIL.COM",
                            NormalizedUserName = "LITTLEJOHN",
                            PasswordHash = "AQAAAAIAAYagAAAAEHgJ1v35yMdrboz2wNnq7ycAFHmE2gEKN5HvTBhtJlXU94370YPUlLqftEVfKcYgPA==",
                            PhoneNumber = "0965765228",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "a6e349c2-faee-4002-ba0b-d1e1ffb4be68",
                            TwoFactorEnabled = false,
                            UserName = "littlejohn",
                            UserRefreshTokenExpiryTime = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6584),
                            isBanned = false,
                            isDeleted = false,
                            isVerified = true
                        },
                        new
                        {
                            Id = "6ad0a020-e6a6-4e66-8f4a-d815594ba862",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3f6f86e9-cd4e-4125-8831-92af06a05941",
                            CreatedDate = new DateTime(2024, 6, 23, 21, 18, 46, 639, DateTimeKind.Local).AddTicks(6596),
                            Email = "kenshiyonezu123@gmail.com",
                            EmailConfirmed = true,
                            EmailVerifyCodeAge = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6597),
                            Gender = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "KENSHIYONEZU123@GMAIL.COM",
                            NormalizedUserName = "KENSHIYONEZU",
                            PasswordHash = "AQAAAAIAAYagAAAAEHgJ1v35yMdrboz2wNnq7ycAFHmE2gEKN5HvTBhtJlXU94370YPUlLqftEVfKcYgPA==",
                            PhoneNumber = "0965765120",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8f774f7d-ecb6-450e-b655-1d06ff2f6348",
                            TwoFactorEnabled = false,
                            UserName = "kenshiyonezu",
                            UserRefreshTokenExpiryTime = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6598),
                            isBanned = false,
                            isDeleted = false,
                            isVerified = true
                        },
                        new
                        {
                            Id = "1c5c3b44-7164-4232-a49a-10ab367d5102",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "674b2afc-8b7c-4a7c-be3a-2f4d48aa03ed",
                            CreatedDate = new DateTime(2024, 6, 23, 21, 18, 46, 639, DateTimeKind.Local).AddTicks(6612),
                            Email = "gakkou123@gmail.com",
                            EmailConfirmed = true,
                            EmailVerifyCodeAge = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6613),
                            Gender = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "GAKKOU123@GMAIL.COM",
                            NormalizedUserName = "GAKKOU",
                            PasswordHash = "AQAAAAIAAYagAAAAEHgJ1v35yMdrboz2wNnq7ycAFHmE2gEKN5HvTBhtJlXU94370YPUlLqftEVfKcYgPA==",
                            PhoneNumber = "0965795220",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "393d041f-5b52-4ae4-982a-477a1f94c437",
                            TwoFactorEnabled = false,
                            UserName = "gakkou",
                            UserRefreshTokenExpiryTime = new DateTime(2024, 6, 23, 14, 18, 46, 639, DateTimeKind.Utc).AddTicks(6614),
                            isBanned = false,
                            isDeleted = false,
                            isVerified = true
                        });
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdDate");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("parentId");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("taskId");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ParentId");

                    b.HasIndex("TaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Entities.Models.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int>("DeviceStatusId")
                        .HasColumnType("int")
                        .HasColumnName("deviceStatusId");

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("datetime2")
                        .HasColumnName("lastUsed");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("name");

                    b.Property<string>("OwnedBy")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("ownedBy");

                    b.Property<bool>("isDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DeviceStatusId");

                    b.HasIndex("OwnedBy");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("Entities.Models.DeviceStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("DeviceStatuses");
                });

            modelBuilder.Entity("Entities.Models.Files", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fileKey");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("folderId");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("mimeType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("name");

                    b.Property<float>("Size")
                        .HasColumnType("real")
                        .HasColumnName("size");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("uploadDate");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Entities.Models.Folder", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdDate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Folders");
                });

            modelBuilder.Entity("Entities.Models.FolderClosure", b =>
                {
                    b.Property<Guid>("AncestorID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ancestor");

                    b.Property<Guid>("DescendantID")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("descendant");

                    b.Property<int>("Depth")
                        .HasColumnType("int")
                        .HasColumnName("depth");

                    b.HasKey("AncestorID", "DescendantID");

                    b.HasIndex("DescendantID");

                    b.ToTable("FoldersClosure");
                });

            modelBuilder.Entity("Entities.Models.Label", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("HexColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .IsUnicode(false)
                        .HasColumnType("char(7)")
                        .HasColumnName("hexColor")
                        .IsFixedLength();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("Entities.Models.Member", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("projectId");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("userId");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("bit")
                        .HasColumnName("isLeader");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("Entities.Models.News", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.ToTable("News");
                });

            modelBuilder.Entity("Entities.Models.NewsFile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("FileKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("fileKey");

                    b.Property<int>("NewsID")
                        .HasColumnType("int")
                        .HasColumnName("newsId");

                    b.HasKey("Id")
                        .HasName("PK_NewsFiles_1");

                    b.HasIndex("NewsID");

                    b.ToTable("NewsFile");
                });

            modelBuilder.Entity("Entities.Models.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(500)
                        .IsUnicode(false)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("content");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdDate");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int")
                        .HasColumnName("notificationTypeId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("NotificationTypeId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Entities.Models.NotificationAccount", b =>
                {
                    b.Property<Guid>("NotificationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("notificationId");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("accountId");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("isRead");

                    b.HasKey("NotificationId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("notificationAccounts");
                });

            modelBuilder.Entity("Entities.Models.NotificationType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("notificationTypes");
                });

            modelBuilder.Entity("Entities.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("Entities.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("description");

                    b.Property<string>("IsRecruiting")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nchar(10)")
                        .HasColumnName("isRecruiting")
                        .IsFixedLength();

                    b.Property<int>("MaxMember")
                        .HasColumnType("int")
                        .HasColumnName("maxMember");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<int>("ProjectStatusId")
                        .HasColumnType("int")
                        .HasColumnName("projectStatusId");

                    b.Property<int>("ProjectTypeId")
                        .HasColumnType("int")
                        .HasColumnName("projectTypeId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectStatusId");

                    b.HasIndex("ProjectTypeId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Entities.Models.ProjectStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ProjectStatuses");
                });

            modelBuilder.Entity("Entities.Models.ProjectType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("ProjectTypes");
                });

            modelBuilder.Entity("Entities.Models.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeviceStatusId")
                        .HasColumnType("int");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("ScheduleId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Entities.Models.Schedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("accountId");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("deviceId");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("endDate");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(250)
                        .IsUnicode(false)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("purpose");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDate");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("DeviceId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Entities.Models.StudentDetail", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("accountId");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("major");

                    b.Property<string>("RollNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("rollNumber");

                    b.Property<string>("Specialized")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("specialized");

                    b.HasKey("AccountId");

                    b.ToTable("StudentDetails");

                    b.HasData(
                        new
                        {
                            AccountId = "603600b5-ca65-4fa7-817e-4583ef22b330",
                            Major = "Software Engineering",
                            RollNumber = "HE163098",
                            Specialized = "ASP.NET"
                        },
                        new
                        {
                            AccountId = "68fdf17c-7cbe-4a4c-a674-c530ffc77667",
                            Major = "Data Engineer",
                            RollNumber = "HE163884",
                            Specialized = "Data Analyst"
                        },
                        new
                        {
                            AccountId = "7397c854-194b-4749-9205-f46e4f2fccf8",
                            Major = "Artifact Intelligent",
                            RollNumber = "HE163956",
                            Specialized = "C"
                        },
                        new
                        {
                            AccountId = "6ad0a020-e6a6-4e66-8f4a-d815594ba862",
                            Major = "Iot",
                            RollNumber = "HE145689",
                            Specialized = "Python"
                        },
                        new
                        {
                            AccountId = "1c5c3b44-7164-4232-a49a-10ab367d5102",
                            Major = "Software Engineering",
                            RollNumber = "HE156894",
                            Specialized = "PHP"
                        });
                });

            modelBuilder.Entity("Entities.Models.TaskHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssignedToUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dueDate");

                    b.Property<DateTime>("EditDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("editDate");

                    b.Property<bool>("RequiredValidation")
                        .HasColumnType("bit")
                        .HasColumnName("requiresValidation");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDate");

                    b.Property<Guid>("TaskGuid")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("taskGuid");

                    b.Property<int>("TaskPriorityId")
                        .HasColumnType("int")
                        .HasColumnName("taskPriorityId");

                    b.Property<int>("TaskStatusId")
                        .HasColumnType("int")
                        .HasColumnName("taskStatusId");

                    b.Property<Guid?>("TasksId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("TaskGuid");

                    b.HasIndex("TaskPriorityId");

                    b.HasIndex("TaskStatusId");

                    b.HasIndex("TasksId");

                    b.ToTable("TaskHistories");
                });

            modelBuilder.Entity("Entities.Models.TaskList", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("MaxTasks")
                        .HasColumnType("int")
                        .HasColumnName("maxTasks");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("projectId");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TaskLists");
                });

            modelBuilder.Entity("Entities.Models.TaskPriorities", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("TaskPriorities");
                });

            modelBuilder.Entity("Entities.Models.Tasks", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("assignedTo");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdBy");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdDate");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("dueDate");

                    b.Property<Guid?>("PredecessorTaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("predecessorTaskId");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("RequiredValidation")
                        .HasColumnType("bit")
                        .HasColumnName("requiresValidation");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("startDate");

                    b.Property<Guid>("TaskListId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("taskListId");

                    b.Property<int>("TaskPriorityId")
                        .HasColumnType("int")
                        .HasColumnName("taskPriorityId");

                    b.Property<int>("TaskStatusId")
                        .HasColumnType("int")
                        .HasColumnName("taskStatusId");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("PredecessorTaskId");

                    b.HasIndex("TaskListId");

                    b.HasIndex("TaskPriorityId");

                    b.HasIndex("TaskStatusId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Entities.Models.TasksStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("TaskStatus", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("SystemRole", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "c55924f5-4cf4-4a29-9820-b5d0d9bdf3c5",
                            Name = "LabAdmin",
                            NormalizedName = "LABADMIN"
                        },
                        new
                        {
                            Id = "cd10e24b-ecbc-4dd0-8141-32c452e1d1c2",
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = "fef2c515-3fe0-4b7d-9f9f-a2ecca647e8d",
                            Name = "Supervisor",
                            NormalizedName = "SUPERVISOR"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AccountClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AccountLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "97571dcc-079e-4c3a-ba9b-bbde3d03a03d",
                            RoleId = "c55924f5-4cf4-4a29-9820-b5d0d9bdf3c5"
                        },
                        new
                        {
                            UserId = "6c6abe62-f811-4a8b-96eb-ed326c47d209",
                            RoleId = "cd10e24b-ecbc-4dd0-8141-32c452e1d1c2"
                        },
                        new
                        {
                            UserId = "a687bb04-4f19-49d5-a60f-2db52044767c",
                            RoleId = "cd10e24b-ecbc-4dd0-8141-32c452e1d1c2"
                        },
                        new
                        {
                            UserId = "603600b5-ca65-4fa7-817e-4583ef22b330",
                            RoleId = "fef2c515-3fe0-4b7d-9f9f-a2ecca647e8d"
                        },
                        new
                        {
                            UserId = "68fdf17c-7cbe-4a4c-a674-c530ffc77667",
                            RoleId = "fef2c515-3fe0-4b7d-9f9f-a2ecca647e8d"
                        },
                        new
                        {
                            UserId = "7397c854-194b-4749-9205-f46e4f2fccf8",
                            RoleId = "fef2c515-3fe0-4b7d-9f9f-a2ecca647e8d"
                        },
                        new
                        {
                            UserId = "6ad0a020-e6a6-4e66-8f4a-d815594ba862",
                            RoleId = "fef2c515-3fe0-4b7d-9f9f-a2ecca647e8d"
                        },
                        new
                        {
                            UserId = "1c5c3b44-7164-4232-a49a-10ab367d5102",
                            RoleId = "fef2c515-3fe0-4b7d-9f9f-a2ecca647e8d"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AccountToken", (string)null);
                });

            modelBuilder.Entity("PermissionProject", b =>
                {
                    b.Property<int>("PermissionsId")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PermissionsId", "ProjectsId");

                    b.HasIndex("ProjectsId");

                    b.ToTable("PermissionProject");
                });

            modelBuilder.Entity("TaskHistoriesLabels", b =>
                {
                    b.Property<Guid>("TaskHistoryId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("taskHistoryId");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("labelId");

                    b.HasKey("TaskHistoryId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("TaskHistoriesLabels", (string)null);
                });

            modelBuilder.Entity("TasksAccount", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("taskId");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("accountId");

                    b.HasKey("TaskId", "AccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("TasksAccounts", (string)null);
                });

            modelBuilder.Entity("TasksFile", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("taskId");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("fileId");

                    b.HasKey("TaskId", "FileId");

                    b.HasIndex("FileId");

                    b.ToTable("TasksFiles", (string)null);
                });

            modelBuilder.Entity("TasksLabel", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("taskId");

                    b.Property<Guid>("LabelId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("labelId");

                    b.HasKey("TaskId", "LabelId");

                    b.HasIndex("LabelId");

                    b.ToTable("TasksLabels", (string)null);
                });

            modelBuilder.Entity("Entities.Models.Account", b =>
                {
                    b.HasOne("Entities.Models.Account", "VerifiedByUser")
                        .WithMany("VerifiedAccounts")
                        .HasForeignKey("VerifiedBy")
                        .HasConstraintName("FK_Accounts_Accounts");

                    b.Navigation("VerifiedByUser");
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.HasOne("Entities.Models.Account", "CreatedByUser")
                        .WithMany("Comments")
                        .HasForeignKey("CreatedBy")
                        .HasConstraintName("FK_Comments_Accounts");

                    b.HasOne("Entities.Models.Comment", "Parent")
                        .WithMany("InverseParent")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("FK_Comments_Comments");

                    b.HasOne("Entities.Models.Tasks", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK_Comments_Tasks");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Parent");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Entities.Models.Device", b =>
                {
                    b.HasOne("Entities.Models.DeviceStatus", "DeviceStatus")
                        .WithMany("Devices")
                        .HasForeignKey("DeviceStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Devices_DeviceStatuses");

                    b.HasOne("Entities.Models.Account", "OwnedByUser")
                        .WithMany("Devices")
                        .HasForeignKey("OwnedBy")
                        .HasConstraintName("FK_Devices_Accounts");

                    b.Navigation("DeviceStatus");

                    b.Navigation("OwnedByUser");
                });

            modelBuilder.Entity("Entities.Models.Files", b =>
                {
                    b.HasOne("Entities.Models.Folder", "Folder")
                        .WithMany("Files")
                        .HasForeignKey("FolderId")
                        .IsRequired()
                        .HasConstraintName("FK_Files_Folders");

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("Entities.Models.Folder", b =>
                {
                    b.HasOne("Entities.Models.Account", "CreatedByUser")
                        .WithMany("Folders")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_Folders_Accounts");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Entities.Models.FolderClosure", b =>
                {
                    b.HasOne("Entities.Models.Folder", "AncestorNavigation")
                        .WithMany("FolderClosureAncestor")
                        .HasForeignKey("AncestorID")
                        .IsRequired()
                        .HasConstraintName("FK_FolderClosures_Folders");

                    b.HasOne("Entities.Models.Folder", "DescendantNavigation")
                        .WithMany("FolderClosureDescendant")
                        .HasForeignKey("DescendantID")
                        .IsRequired()
                        .HasConstraintName("FK_FolderClosures_Folders1");

                    b.Navigation("AncestorNavigation");

                    b.Navigation("DescendantNavigation");
                });

            modelBuilder.Entity("Entities.Models.Member", b =>
                {
                    b.HasOne("Entities.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_Members_Projects");

                    b.HasOne("Entities.Models.Account", "User")
                        .WithMany("Members")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_Members_Accounts");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entities.Models.News", b =>
                {
                    b.HasOne("Entities.Models.Account", "CreatedByNavigation")
                        .WithMany("News")
                        .HasForeignKey("CreatedBy")
                        .IsRequired()
                        .HasConstraintName("FK_News_Accounts");

                    b.Navigation("CreatedByNavigation");
                });

            modelBuilder.Entity("Entities.Models.NewsFile", b =>
                {
                    b.HasOne("Entities.Models.News", "News")
                        .WithMany("NewsFiles")
                        .HasForeignKey("NewsID")
                        .IsRequired()
                        .HasConstraintName("FK_NewsFiles_News1");

                    b.Navigation("News");
                });

            modelBuilder.Entity("Entities.Models.Notification", b =>
                {
                    b.HasOne("Entities.Models.Account", "CreatedByUser")
                        .WithMany("Notifications")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_Accounts");

                    b.HasOne("Entities.Models.NotificationType", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Notifications_NotificationTypes");

                    b.Navigation("CreatedByUser");

                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("Entities.Models.NotificationAccount", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("NotificationsAccounts")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationsAccounts_Accounts");

                    b.HasOne("Entities.Models.Notification", "Notification")
                        .WithMany("NotificationsAccounts")
                        .HasForeignKey("NotificationId")
                        .IsRequired()
                        .HasConstraintName("FK_NotificationsAccounts_Notifications");

                    b.Navigation("Account");

                    b.Navigation("Notification");
                });

            modelBuilder.Entity("Entities.Models.Project", b =>
                {
                    b.HasOne("Entities.Models.ProjectStatus", "ProjectStatus")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Projects_ProjectStatuses");

                    b.HasOne("Entities.Models.ProjectType", "ProjectType")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Projects_ProjectTypes");

                    b.Navigation("ProjectStatus");

                    b.Navigation("ProjectType");
                });

            modelBuilder.Entity("Entities.Models.Report", b =>
                {
                    b.HasOne("Entities.Models.Account", null)
                        .WithMany("Reports")
                        .HasForeignKey("AccountId");

                    b.HasOne("Entities.Models.Schedule", "Schedules")
                        .WithOne("Report")
                        .HasForeignKey("Entities.Models.Report", "ScheduleId")
                        .IsRequired()
                        .HasConstraintName("FK_Reports_Schedules");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Entities.Models.Schedule", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithMany("Schedules")
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Accounts");

                    b.HasOne("Entities.Models.Device", "Device")
                        .WithMany("Schedules")
                        .HasForeignKey("DeviceId")
                        .IsRequired()
                        .HasConstraintName("FK_Schedules_Devices");

                    b.Navigation("Account");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Entities.Models.StudentDetail", b =>
                {
                    b.HasOne("Entities.Models.Account", "Account")
                        .WithOne("StudentDetail")
                        .HasForeignKey("Entities.Models.StudentDetail", "AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_StudentDetails_Accounts");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Entities.Models.TaskHistory", b =>
                {
                    b.HasOne("Entities.Models.Account", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Tasks", "TaskVersion")
                        .WithMany()
                        .HasForeignKey("TaskGuid")
                        .IsRequired()
                        .HasConstraintName("FK_TaskHistories_Tasks");

                    b.HasOne("Entities.Models.TaskPriorities", "TaskPriority")
                        .WithMany()
                        .HasForeignKey("TaskPriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TaskHistories_TaskPrioties");

                    b.HasOne("Entities.Models.TasksStatus", "TaskStatus")
                        .WithMany()
                        .HasForeignKey("TaskStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_TaskHistories_TaskStatus");

                    b.HasOne("Entities.Models.Tasks", null)
                        .WithMany("TaskHistories")
                        .HasForeignKey("TasksId");

                    b.Navigation("AssignedToUser");

                    b.Navigation("TaskPriority");

                    b.Navigation("TaskStatus");

                    b.Navigation("TaskVersion");
                });

            modelBuilder.Entity("Entities.Models.TaskList", b =>
                {
                    b.HasOne("Entities.Models.Project", "Project")
                        .WithMany("TaskLists")
                        .HasForeignKey("ProjectId")
                        .IsRequired()
                        .HasConstraintName("FK_TaskLists_Projects");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Entities.Models.Tasks", b =>
                {
                    b.HasOne("Entities.Models.Account", "AssignedToUser")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedTo")
                        .HasConstraintName("FK_Tasks_Accounts");

                    b.HasOne("Entities.Models.Tasks", "PredecessorTask")
                        .WithMany("InversePredecessorTask")
                        .HasForeignKey("PredecessorTaskId")
                        .HasConstraintName("FK_Tasks_Tasks");

                    b.HasOne("Entities.Models.TaskList", "TaskList")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskListId")
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_TaskLists");

                    b.HasOne("Entities.Models.TaskPriorities", "TaskPriority")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskPriorityId")
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_TaskPrioties");

                    b.HasOne("Entities.Models.TasksStatus", "TaskStatus")
                        .WithMany("Tasks")
                        .HasForeignKey("TaskStatusId")
                        .IsRequired()
                        .HasConstraintName("FK_Tasks_TaskStatus");

                    b.Navigation("AssignedToUser");

                    b.Navigation("PredecessorTask");

                    b.Navigation("TaskList");

                    b.Navigation("TaskPriority");

                    b.Navigation("TaskStatus");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PermissionProject", b =>
                {
                    b.HasOne("Entities.Models.Permission", null)
                        .WithMany()
                        .HasForeignKey("PermissionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskHistoriesLabels", b =>
                {
                    b.HasOne("Entities.Models.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .IsRequired()
                        .HasConstraintName("FK_TaskHistoriesLabels_Labels");

                    b.HasOne("Entities.Models.TaskHistory", null)
                        .WithMany()
                        .HasForeignKey("TaskHistoryId")
                        .IsRequired()
                        .HasConstraintName("FK_TaskHistoriesLabels_TaskHistories");
                });

            modelBuilder.Entity("TasksAccount", b =>
                {
                    b.HasOne("Entities.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .IsRequired()
                        .HasConstraintName("FK_TasksAccounts_Accounts");

                    b.HasOne("Entities.Models.Tasks", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK_TasksAccounts_Tasks");
                });

            modelBuilder.Entity("TasksFile", b =>
                {
                    b.HasOne("Entities.Models.Files", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .IsRequired()
                        .HasConstraintName("FK_TasksFiles_Files");

                    b.HasOne("Entities.Models.Tasks", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK_TasksFiles_Tasks");
                });

            modelBuilder.Entity("TasksLabel", b =>
                {
                    b.HasOne("Entities.Models.Label", null)
                        .WithMany()
                        .HasForeignKey("LabelId")
                        .IsRequired()
                        .HasConstraintName("FK_TasksLabels_Labels");

                    b.HasOne("Entities.Models.Tasks", null)
                        .WithMany()
                        .HasForeignKey("TaskId")
                        .IsRequired()
                        .HasConstraintName("FK_TasksLabels_Tasks");
                });

            modelBuilder.Entity("Entities.Models.Account", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Devices");

                    b.Navigation("Folders");

                    b.Navigation("Members");

                    b.Navigation("News");

                    b.Navigation("Notifications");

                    b.Navigation("NotificationsAccounts");

                    b.Navigation("Reports");

                    b.Navigation("Schedules");

                    b.Navigation("StudentDetail");

                    b.Navigation("Tasks");

                    b.Navigation("VerifiedAccounts");
                });

            modelBuilder.Entity("Entities.Models.Comment", b =>
                {
                    b.Navigation("InverseParent");
                });

            modelBuilder.Entity("Entities.Models.Device", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Entities.Models.DeviceStatus", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Entities.Models.Folder", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("FolderClosureAncestor");

                    b.Navigation("FolderClosureDescendant");
                });

            modelBuilder.Entity("Entities.Models.News", b =>
                {
                    b.Navigation("NewsFiles");
                });

            modelBuilder.Entity("Entities.Models.Notification", b =>
                {
                    b.Navigation("NotificationsAccounts");
                });

            modelBuilder.Entity("Entities.Models.NotificationType", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Entities.Models.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("TaskLists");
                });

            modelBuilder.Entity("Entities.Models.ProjectStatus", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Entities.Models.ProjectType", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Entities.Models.Schedule", b =>
                {
                    b.Navigation("Report");
                });

            modelBuilder.Entity("Entities.Models.TaskList", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Entities.Models.TaskPriorities", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Entities.Models.Tasks", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("InversePredecessorTask");

                    b.Navigation("TaskHistories");
                });

            modelBuilder.Entity("Entities.Models.TasksStatus", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
