export const ERROR = {
  IS_BANNED: 'ISBANNED',
  UNVERIFIED: 'UNVERIFIED',
  NETWORK: 'ERR_NETWORK'
} as const;

export const ROLES = {
  LAB_ADMIN: 'LABADMIN',
  STUDENT: 'STUDENT',
  SUPERVISOR: 'SUPERVISOR'
} as const;
