name: Backend CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    environment: BACKEND_ENV
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Create appsettings.json from base64 secret
        run: echo "${{ secrets.APPSETTINGS_JSON }}" | base64 -d > ./LMS_BACKEND/LMS_BACKEND_MAIN/appsettings.json

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: List files for debugging
        run: |
          ls -al
          ls -al ./LMS_BACKEND
          ls -al ./LMS_BACKEND/LMS_BACKEND_MAIN

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
           context: ./LMS_BACKEND
           file: ./LMS_BACKEND/LMS_BACKEND_MAIN/Dockerfile
           push: true
           tags: ${{ secrets.DOCKER_USERNAME }}/lms-backend:latest

  deploy-backend:
    needs: build-and-push-backend
    runs-on: ubuntu-latest
  
    environment: BACKEND_ENV
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install awscli
          aws --version
  
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2  
  
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client
  
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tee ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
  
      - name: Deploy to EC2
        env:
          ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          SERVICE_URL: ${{ secrets.SERVICE_URL }}
          EMAILADMIN: ${{ secrets.EMAILADMIN }}
        run: |
          ssh -o "StrictHostKeyChecking=no" ec2-user@${{ secrets.EC2_IP }} << 'EOF'
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            docker pull ${{ secrets.DOCKER_USERNAME }}/lms-backend:latest

            docker stop lms-backend-container || true
            docker rm lms-backend-container || true

            docker run -d -p 80:80 --name lms-backend-container \
              -e ACCESS_KEY=${{ secrets.ACCESS_KEY }} \
              -e SECRET_KEY=${{ secrets.SECRET_KEY }} \
              -e SERVICE_URL=${{ secrets.SERVICE_URL }} \
              -e EMAILADMIN=${{ secrets.EMAILADMIN }} \
              ${{ secrets.DOCKER_USERNAME }}/lms-backend:latest
          EOF
